package:
  name: plio
  version: 0.1.0

source:
  path: ../

build:
  number: 0
  skip: true  #[win]
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pvl
    - protobuf 3.0.0b2
    - gdal
    - icu
    - h5py
    - pandas
    - sqlalchemy
    - pyyaml
    - affine
    - networkx
  run:
    - python
    - setuptools
    - numpy
    - pvl
    - protobuf 3.0.0b2
    - gdal
    - icu
    - h5py
    - pandas
    - sqlalchemy
    - pyyaml
    - affine
    - networkx

test:
  imports:
    - plio

about:
  home: http://github.com/USGS-Astrogeology/plio
  license: Public Domain
